'use strict';

const log = require('./logger')('email-digest');

function getConfig() {
  return {
    smtpHost: process.env.SMTP_HOST || '',
    smtpPort: parseInt(process.env.SMTP_PORT, 10) || 587,
    smtpSecure: String(process.env.SMTP_SECURE || '').toLowerCase() === 'true',
    smtpUser: process.env.SMTP_USER || '',
    smtpPass: process.env.SMTP_PASS || '',
    smtpFrom: process.env.SMTP_FROM || process.env.SMTP_USER || '',
    digestTo: process.env.DIGEST_TO || '',
    minScore: parseInt(process.env.DIGEST_MIN_SCORE, 10) || 6,
    maxJobs: parseInt(process.env.DIGEST_MAX_JOBS, 10) || 25,
    lookbackHours: parseInt(process.env.DIGEST_LOOKBACK_HOURS, 10) || 26,
  };
}

function queryJobs(db, { minScore, maxJobs, lookbackHours }) {
  return db.prepare(`
    SELECT id, title, company, url, score, reasoning, location, created_at
    FROM jobs
    WHERE score >= ?
      AND status != 'archived'
      AND datetime(created_at) >= datetime('now', ? || ' hours')
    ORDER BY score DESC
    LIMIT ?
  `).all(minScore, `-${lookbackHours}`, maxJobs);
}

function scoreColor(score) {
  if (score >= 8) return '#16a34a';
  if (score >= 6) return '#ca8a04';
  return '#dc2626';
}

function buildHtml(jobs, { minScore, date }) {
  const jobCards = jobs.map((job) => {
    const reasoning = (job.reasoning || '').slice(0, 160).replace(/</g, '&lt;').replace(/>/g, '&gt;');
    const title = (job.title || '').replace(/</g, '&lt;');
    const company = (job.company || '').replace(/</g, '&lt;');
    const location = (job.location || '').replace(/</g, '&lt;');
    const url = job.url || '#';
    const color = scoreColor(job.score);

    return `
    <tr>
      <td style="padding:12px 16px;border-bottom:1px solid #e5e7eb;vertical-align:top">
        <div style="margin-bottom:4px">
          <a href="${url}" style="font-size:15px;font-weight:600;color:#1d4ed8;text-decoration:none">${title}</a>
          <span style="display:inline-block;margin-left:8px;padding:2px 8px;border-radius:9999px;background:${color};color:#fff;font-size:12px;font-weight:700">${job.score}/10</span>
        </div>
        <div style="font-size:13px;color:#374151;margin-bottom:4px">${company}${location ? ` &mdash; ${location}` : ''}</div>
        ${reasoning ? `<div style="font-size:12px;color:#6b7280;line-height:1.5">${reasoning}${reasoning.length >= 160 ? '&hellip;' : ''}</div>` : ''}
      </td>
    </tr>`;
  }).join('');

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f9fafb;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif">
  <table width="100%" cellpadding="0" cellspacing="0" style="max-width:680px;margin:32px auto;background:#fff;border-radius:8px;box-shadow:0 1px 3px rgba(0,0,0,.1)">
    <tr>
      <td style="padding:24px 24px 16px;border-bottom:2px solid #e5e7eb">
        <h1 style="margin:0;font-size:20px;color:#111827">Job Search Digest</h1>
        <p style="margin:4px 0 0;font-size:13px;color:#6b7280">${date} &mdash; ${jobs.length} job${jobs.length !== 1 ? 's' : ''} scored ${minScore}+</p>
      </td>
    </tr>
    <tr>
      <td style="padding:0">
        <table width="100%" cellpadding="0" cellspacing="0">
          ${jobCards}
        </table>
      </td>
    </tr>
    <tr>
      <td style="padding:16px 24px;border-top:1px solid #e5e7eb;font-size:11px;color:#9ca3af;text-align:center">
        Generated by job-search-automation
      </td>
    </tr>
  </table>
</body>
</html>`;
}

async function sendEmailDigest(db) {
  const config = getConfig();

  if (!config.smtpHost || !config.digestTo) {
    log.info('Email digest skipped: SMTP_HOST or DIGEST_TO not configured');
    return { sent: false, count: 0 };
  }

  let nodemailer;
  try {
    nodemailer = require('nodemailer');
  } catch (e) {
    log.warn('nodemailer not installed; skipping digest. Run: npm install nodemailer');
    return { sent: false, count: 0 };
  }

  const jobs = queryJobs(db, config);
  if (!jobs.length) {
    log.info('Email digest: no qualifying jobs, skipping send');
    return { sent: false, count: 0 };
  }

  const date = new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
  const subject = `Job Search Digest — ${date}: ${jobs.length} new job${jobs.length !== 1 ? 's' : ''} scored ${config.minScore}+`;
  const html = buildHtml(jobs, { minScore: config.minScore, date });

  const transporter = nodemailer.createTransport({
    host: config.smtpHost,
    port: config.smtpPort,
    secure: config.smtpSecure,
    auth: config.smtpUser ? { user: config.smtpUser, pass: config.smtpPass } : undefined,
  });

  try {
    await transporter.sendMail({
      from: config.smtpFrom,
      to: config.digestTo,
      subject,
      html,
    });
    log.info('Email digest sent', { to: config.digestTo, count: jobs.length, subject });
    return { sent: true, count: jobs.length };
  } catch (e) {
    log.error('Email digest send failed', { error: e.message });
    return { sent: false, count: 0 };
  }
}

module.exports = { sendEmailDigest };
