#Requires -RunAsAdministrator
<#
.SYNOPSIS
    Registers a Windows Task Scheduler job that runs the job-search pipeline daily.

.DESCRIPTION
    Creates a scheduled task called "JobSearchAutomation" that runs
    node scripts/refresh.js once per day. Output is logged to logs/scheduler.log
    in the repo directory.

    The task uses the Claude CLI for LLM scoring (no Groq API key needed).
    Make sure `claude` is installed and authenticated before running this.

.PARAMETER Time
    Time of day to run the pipeline (24-hour HH:MM). Default: 08:00.

.PARAMETER Disable
    Remove (unregister) the scheduled task instead of creating it.

.EXAMPLE
    # Register task to run at 8:00 AM daily
    powershell -ExecutionPolicy Bypass -File scripts\setup-task-scheduler.ps1

.EXAMPLE
    # Change run time to 7:30 AM
    powershell -ExecutionPolicy Bypass -File scripts\setup-task-scheduler.ps1 -Time 07:30

.EXAMPLE
    # Remove the task
    powershell -ExecutionPolicy Bypass -File scripts\setup-task-scheduler.ps1 -Disable
#>

param(
    [string]$Time = "08:00",
    [switch]$Disable
)

$TaskName = "JobSearchAutomation"

# ── Paths ────────────────────────────────────────────────────────────────────
$RepoRoot    = Split-Path -Parent $PSScriptRoot
$NodeExe     = (Get-Command node -ErrorAction SilentlyContinue)?.Source
$ClaudeExe   = (Get-Command claude -ErrorAction SilentlyContinue)?.Source
$LogDir      = Join-Path $RepoRoot "logs"
$LogFile     = Join-Path $LogDir "scheduler.log"
$WrapperPath = Join-Path $RepoRoot "scripts\run-pipeline.ps1"

# ── Remove mode ──────────────────────────────────────────────────────────────
if ($Disable) {
    $existing = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
    if ($existing) {
        Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
        Write-Host "Task '$TaskName' removed."
    } else {
        Write-Host "Task '$TaskName' not found — nothing to remove."
    }
    exit 0
}

# ── Preflight ─────────────────────────────────────────────────────────────────
if (-not $NodeExe) {
    Write-Error "node.exe not found in PATH. Install Node.js from https://nodejs.org"
    exit 1
}
if (-not $ClaudeExe) {
    Write-Warning "claude not found in PATH. Make sure Claude Code is installed and 'claude' is on PATH."
    Write-Warning "The task will be created but scoring will fail until claude is available."
    $ClaudeExe = "claude"
}
if (-not (Test-Path (Join-Path $RepoRoot ".env"))) {
    Write-Warning ".env file not found at $RepoRoot\.env — copy .env.example and fill it in before running."
}

New-Item -ItemType Directory -Force -Path $LogDir | Out-Null

# ── Write the inner runner script ─────────────────────────────────────────────
# Task Scheduler runs in a minimal environment; this wrapper sets the working
# directory, sets CLAUDE_CODE_EXECPATH so the pipeline finds the CLI, and
# timestamps log entries.
@"
# Auto-generated by setup-task-scheduler.ps1 — do not edit manually.
Set-Location "$RepoRoot"
`$env:CLAUDE_CODE_EXECPATH = "$ClaudeExe"
`$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
Add-Content "$LogFile" "`n=== Pipeline run started at `$timestamp ==="
& "$NodeExe" scripts\refresh.js --skip-discover --skip-closed-check --skip-market-research --skip-slug-check 2>&1 |
    ForEach-Object { Add-Content "$LogFile" `$_ }
& "$NodeExe" scripts\send-email-digest.js 2>&1 |
    ForEach-Object { Add-Content "$LogFile" `$_ }
Add-Content "$LogFile" "=== Pipeline run finished at `$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss') ==="
"@ | Set-Content $WrapperPath -Encoding UTF8

Write-Host "Wrapper script written to: $WrapperPath"

# ── Parse run time ────────────────────────────────────────────────────────────
$timeParts = $Time -split ":"
if ($timeParts.Length -ne 2) {
    Write-Error "Invalid -Time format. Use HH:MM (e.g. 08:00)."
    exit 1
}
[int]$Hour   = $timeParts[0]
[int]$Minute = $timeParts[1]

# ── Build Task Scheduler objects ──────────────────────────────────────────────
$trigger = New-ScheduledTaskTrigger -Daily -At "$($Hour.ToString('D2')):$($Minute.ToString('D2'))"

$action = New-ScheduledTaskAction `
    -Execute "powershell.exe" `
    -Argument "-NonInteractive -ExecutionPolicy Bypass -File `"$WrapperPath`"" `
    -WorkingDirectory $RepoRoot

# Run as the current user so Claude CLI auth is available.
$principal = New-ScheduledTaskPrincipal `
    -UserId "$env:USERDOMAIN\$env:USERNAME" `
    -LogonType Interactive `
    -RunLevel Highest

$settings = New-ScheduledTaskSettingsSet `
    -StartWhenAvailable `
    -WakeToRun:$false `
    -ExecutionTimeLimit (New-TimeSpan -Hours 2) `
    -MultipleInstances IgnoreNew

# ── Register (or replace) ─────────────────────────────────────────────────────
$existing = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
if ($existing) {
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
    Write-Host "Replaced existing task '$TaskName'."
}

Register-ScheduledTask `
    -TaskName $TaskName `
    -Trigger $trigger `
    -Action $action `
    -Principal $principal `
    -Settings $settings `
    -Description "Daily job-search pipeline using Claude CLI for scoring. Repo: $RepoRoot" | Out-Null

Write-Host ""
Write-Host "Task '$TaskName' registered successfully."
Write-Host "  Schedule  : Daily at $Time"
Write-Host "  Node      : $NodeExe"
Write-Host "  Claude CLI: $ClaudeExe"
Write-Host "  Repo      : $RepoRoot"
Write-Host "  Log file  : $LogFile"
Write-Host ""
Write-Host "Run 'Get-ScheduledTask -TaskName $TaskName' to verify."
Write-Host "Run 'Start-ScheduledTask -TaskName $TaskName' to trigger a manual run."
